name: Reusable Backend Test

on:
  workflow_call:
    inputs:
      artifact_name:
        description: 'The name of the tarantool build artifact'
        default: ubuntu-focal
        required: false
        type: string

env:
  # Skip building frontend in `tarantoolctl rocks make`
  CMAKE_DUMMY_WEBUI: true
  # Prerequisite for some etcd-related tests
  ETCD_PATH: etcd-v2.3.8/etcd

jobs:
  run_tests:
    runs-on: self-hosted
    steps:
      - name: 'Clone the cartridge module'
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository_owner }}/cartridge

      # Setup tarantool
      - name: 'Download the tarantool build artifact'
        uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.artifact_name }}
      # TODO(ylobankov): Just in case remove tarantool that could be previously
      # installed on the runner. Relevant to self-hosted runners. Remove this
      # step when only GitHub-hosted runners are used for integration testing.
      - run: sudo apt-get -y purge 'tarantool*'
      - name: 'Install tarantool'
        # TODO(ylobankov): Install package dependencies. Now we're lucky: all
        # dependencies are already there.
        run: sudo dpkg -i tarantool*.deb

      # Setup etcd
      - name: 'Install etcd'
        uses: ./.github/actions/setup-etcd
        with:
          etcd-version: v2.3.8
          install-prefix: etcd-v2.3.8

      # Setup luatest
      - name: 'Install luatest'
        run: tarantoolctl rocks install luatest 0.5.6

      # Setup pytest
      - name: 'Install pytest'
        run: |
          python -m venv ./pytest-venv && . ./pytest-venv/bin/activate
          pip install -r test/integration/requirements.txt

      - name: 'Install cartridge'
        run: tarantoolctl rocks make

      - name: 'Run luatest'
        run: .rocks/bin/luatest -v

      - name: 'Run pytest'
        run: |
          . ./pytest-venv/bin/activate
          pytest -v

      # Cleanup cached paths
      - run: tarantoolctl rocks remove cartridge

      # TODO(ylobankov): Relevant to self-hosted runners. Remove this step
      # when only GitHub-hosted runners are used for integration testing.
      - if: always()
        run: sudo apt-get -y purge 'tarantool*'
